name: Trigger auto deployment for conteinaerappsdiccionary

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/conteinaerappsdiccionary-AutoDeployTrigger-e5b1a470-759f-4062-8fc5-fbb0992e8a44.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTEINAERAPPSDICCIONARY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrypersonal.azurecr.io
          registryUsername: ${{ secrets.CONTEINAERAPPSDICCIONARY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTEINAERAPPSDICCIONARY_REGISTRY_PASSWORD }}
          containerAppName: conteinaerappsdiccionary
          resourceGroup: gp-projectDiccionarioITCA
          imageToBuild: containerregistrypersonal.azurecr.io/conteinaerappsdiccionary:${{ github.sha }}
          

     

